#!/bin/bash

echo "🚀 Lumaa AI Dashboard - Supervisor Mode"
echo "======================================="
echo ""
echo "✅ Services already running via supervisor:"
echo "  - Backend (Express.js): Port 8001"
echo "  - Frontend (React): Port 3000" 
echo "  - Database (PostgreSQL): Connected"
echo ""
echo "🌐 Access your application:"
echo "  Dashboard: Available via your domain"
echo ""
echo "📋 Service Management:"
echo "  - Status: sudo supervisorctl status"
echo "  - Restart: sudo supervisorctl restart all"
echo "  - Stop: sudo supervisorctl stop all"
echo ""
echo "🔧 Development Commands:"
echo "  - Backend logs: tail -f /var/log/supervisor/backend.*.log"
echo "  - Frontend logs: tail -f /var/log/supervisor/frontend.*.log"
echo ""
echo "Ready! 🎉"